#!/usr/bin/env node
// regen-r.mjs — regenerate patches/FinalPersonalizeR.patch from the dev tree.
//
// WHY THIS EXISTS (and why it is not regen-personalize.ps1):
//   regen-personalize.ps1 only ever rebuilds FinalPERSONALIZE.patch ($CoreFiles) and
//   FinalPersonalizeX.patch ($XFiles). Neither list contains tool/custom.ts, so the R
//   patch — the one carrying the custom tool block (council/distill/schedule) — was
//   regenerated by hand every time and silently went stale. This is that job, scripted.
//
// WHY NODE AND NOT `git diff`:
//   There is no git binary on this box (CommandNotFoundException). R is structurally
//   trivial to rebuild without one: tool/custom.ts is a *new file*, so its diff body is
//   just the whole file with '+' in front. That is reproduced here byte-exactly,
//   including the git blob SHAs in the `index` line.
//
// WHAT IT DOES PER FILE SECTION:
//   new file  (--- /dev/null) -> rebuilt from disk: LF-normalized body, @@ -0,0 +1,N @@,
//                                index 000000000..<sha1(blob)> <mode>.
//   modified  (real a/ side)  -> preserved BYTE-FOR-BYTE. Two reasons it is never rewritten:
//                                (1) no upstream pre-image is available offline, and
//                                (2) its post-image is the state after CORE->X->S->R apply
//                                    to pristine upstream, which is NOT the dev tree - the
//                                    dev tree carries extra lines from the other patches.
//                                    Recomputing the b-side blob SHA from disk would write a
//                                    SHA for the wrong blob and break `git apply --3way`.
//                                They are still checked: each hunk's post-image (' ' and '+'
//                                lines) must appear in the dev tree as a contiguous block.
//                                The match is OFFSET-TOLERANT on purpose - a shifted line
//                                number is exactly what --3way re-anchors by context, and the
//                                recorded CORE->X->S->R validation passed with these offsets.
//                                A block that cannot be found at all is a hard error: that
//                                means the customization is gone from the dev tree.
//
// USAGE:
//   node regen-r.mjs             # verify + rewrite if changed
//   node regen-r.mjs --check     # verify only, non-zero exit if stale (CI-safe)
//
// INVARIANTS ENFORCED: LF only (this harness's editors emit CRLF), trailing-newline
// marker handled, atomic write, .bak kept, round-trip re-parse of the emitted patch.

import { readFileSync, writeFileSync, renameSync, existsSync, copyFileSync } from "node:fs"
import { createHash } from "node:crypto"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const PATCH = join(HERE, "patches", "FinalPersonalizeR.patch")
// The dev tree the patch is cut from. R's sources live in the finalsnap working copy.
const DEV = join(HERE, "..", "finalsnap")

const CHECK = process.argv.includes("--check")
const log = (...a) => console.log(...a)
const fail = (m) => {
  console.error("FAIL: " + m)
  process.exit(1)
}

const lf = (s) => s.replace(/\r\n/g, "\n")
const blobSha = (text) => {
  const body = Buffer.from(text, "utf8")
  const h = createHash("sha1")
  h.update(Buffer.from(`blob ${body.length}\0`, "utf8"))
  h.update(body)
  return h.digest("hex")
}
// git abbreviates to 9 in this patch set; keep it identical so diffs stay reviewable.
const ABBREV = 9
const short = (sha) => sha.slice(0, ABBREV)

// ---- parse the existing patch into per-file sections -----------------------------
const original = readFileSync(PATCH, "utf8")
if (original.includes("\r")) fail("existing patch already contains CR bytes - refusing to work from a poisoned file")
const lines = original.split("\n")
const trailingNewline = lines[lines.length - 1] === ""
if (trailingNewline) lines.pop()

const starts = []
lines.forEach((l, i) => l.startsWith("diff --git ") && starts.push(i))
if (!starts.length) fail("no `diff --git` sections found in " + PATCH)

const sections = starts.map((s, i) => {
  const end = i + 1 < starts.length ? starts[i + 1] : lines.length
  const body = lines.slice(s, end)
  const m = body[0].match(/^diff --git a\/(.+) b\/(.+)$/)
  if (!m) fail("unparsable diff header: " + body[0])
  if (m[1] !== m[2]) fail("rename detected, not supported: " + body[0])
  return { path: m[1], lines: body }
})

// ---- rebuild ---------------------------------------------------------------------
const out = []
let changed = 0
const report = []

for (const sec of sections) {
  const disk = join(DEV, sec.path.replace(/\//g, "\\"))
  if (!existsSync(disk)) fail(`${sec.path}: not found in dev tree at ${disk}`)
  const text = lf(readFileSync(disk, "utf8"))
  const isNew = sec.lines.some((l) => l === "--- /dev/null")

  if (isNew) {
    const modeLine = sec.lines.find((l) => /^new file mode /.test(l)) ?? "new file mode 100644"
    const mode = modeLine.split(" ").pop()
    const oldIdx = sec.lines.find((l) => l.startsWith("index ")) ?? ""
    const endsNL = text.endsWith("\n")
    const body = (endsNL ? text.slice(0, -1) : text).split("\n")
    const rebuilt = [
      `diff --git a/${sec.path} b/${sec.path}`,
      modeLine,
      `index ${"0".repeat(ABBREV)}..${short(blobSha(text))} ${mode}`,
      "--- /dev/null",
      `+++ b/${sec.path}`,
      `@@ -0,0 +1,${body.length} @@`,
      ...body.map((l) => "+" + l),
    ]
    if (!endsNL) rebuilt.push("\\ No newline at end of file")
    const same = rebuilt.join("\n") === sec.lines.join("\n")
    if (!same) changed++
    report.push(
      `  ${same ? "unchanged" : "REBUILT  "}  ${sec.path}  (new file, ${body.length} lines)` +
        (same ? "" : `\n                 ${oldIdx.trim()}\n              -> index ${"0".repeat(ABBREV)}..${short(blobSha(text))} ${mode}`),
    )
    out.push(...rebuilt)
    continue
  }

  // modified file: verify every hunk's post-image against the dev tree, recompute b-sha
  const diskLines = text.endsWith("\n") ? text.slice(0, -1).split("\n") : text.split("\n")
  const hunkNotes = []
  let i = 0
  for (; i < sec.lines.length; i++) {
    const h = sec.lines[i].match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/)
    if (!h) continue
    const startLine = Number(h[1])
    const count = h[2] === undefined ? 1 : Number(h[2])
    const post = []
    for (let j = i + 1; j < sec.lines.length; j++) {
      const l = sec.lines[j]
      if (l.startsWith("@@ ") || l.startsWith("diff --git ")) break
      if (l.startsWith("\\")) continue
      if (l.startsWith(" ") || l.startsWith("+")) post.push(l.slice(1))
      else if (!l.startsWith("-")) break
    }
    if (post.length !== count)
      fail(`${sec.path}: hunk claims +${count} lines but carries ${post.length}`)

    // Offset-tolerant search: find the post-image block anywhere in the dev tree,
    // preferring the line the hunk claims. Anchor on the first '+' line so a block of
    // pure context cannot match the wrong place.
    const at = []
    for (let s = 0; s + count <= diskLines.length; s++) {
      let ok = true
      for (let k = 0; k < count; k++)
        if (diskLines[s + k] !== post[k]) {
          ok = false
          break
        }
      if (ok) at.push(s + 1)
    }
    if (!at.length) {
      const added = []
      for (let j = i + 1; j < sec.lines.length; j++) {
        const l = sec.lines[j]
        if (l.startsWith("@@ ") || l.startsWith("diff --git ")) break
        if (l.startsWith("+")) added.push(l.slice(1))
      }
      const missing = added.filter((a) => !diskLines.includes(a))
      fail(
        `${sec.path}: hunk @@ +${startLine},${count} @@ has no match anywhere in the dev tree.\n` +
          (missing.length
            ? `   These added lines are absent from the dev tree:\n` +
              missing.map((m) => `     ${JSON.stringify(m)}`).join("\n") + "\n"
            : `   All '+' lines exist but not as one contiguous block - surrounding context moved.\n`) +
          `   The customization is not in the dev tree as the patch describes it. Fix the dev\n` +
          `   tree, or regen this file's hunks against upstream with git diff.`,
      )
    }
    if (!at.includes(startLine))
      hunkNotes.push(`offset ${at[0] - startLine >= 0 ? "+" : ""}${at[0] - startLine} (patch says ${startLine}, dev tree ${at[0]})`)
    else hunkNotes.push("exact")
  }
  // verbatim - see header comment: the b-side blob is the post-chain state, not this file
  report.push(
    `  verified   ${sec.path}  (modified, ${hunkNotes.length} hunks: ${hunkNotes.join("; ")}) kept verbatim`,
  )
  out.push(...sec.lines)
}

const next = out.join("\n") + (trailingNewline ? "\n" : "")

// ---- round-trip the emitted patch before it touches disk -------------------------
if (next.includes("\r")) fail("refusing to write: generated patch contains CR")
const reStarts = next.split("\n").filter((l) => l.startsWith("diff --git ")).length
if (reStarts !== sections.length) fail(`section count changed ${sections.length} -> ${reStarts}`)
for (const sec of sections) {
  if (!next.includes(`diff --git a/${sec.path} b/${sec.path}`)) fail("lost section " + sec.path)
}

log("FinalPersonalizeR.patch")
log(report.join("\n"))

if (next === original) {
  log("\nRESULT: already up to date (no write).")
  process.exit(0)
}

const before = Buffer.byteLength(original, "utf8")
const after = Buffer.byteLength(next, "utf8")
log(`\nRESULT: STALE -> regenerated. ${before} bytes -> ${after} bytes (${lines.length} -> ${next.split("\n").length - (trailingNewline ? 1 : 0)} lines)`)

if (CHECK) {
  console.error("--check: patch is stale, not written. Run without --check to update.")
  process.exit(2)
}

copyFileSync(PATCH, PATCH + ".bak")
const tmp = PATCH + ".tmp"
writeFileSync(tmp, next, { encoding: "utf8" })
renameSync(tmp, PATCH)
const verify = readFileSync(PATCH, "utf8")
if (verify !== next) fail("post-write verification mismatch")
log(`written: ${PATCH}\nbackup : ${PATCH}.bak`)
